# Generated by Django 5.2.14 on 2026-05-22 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goal', models.CharField(blank=True, max_length=300)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('available_hours_per_week', models.IntegerField(default=5)),
                ('streak_days', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('xp_points', models.IntegerField(default=0)),
                ('badge_count', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
