# Generated by Django 5.2.14 on 2026-05-22 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes_studied', models.IntegerField(default=0)),
                ('concepts_completed', models.IntegerField(default=0)),
                ('videos_watched', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='users.userprofile')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
