# Generated by Django 5.2.14 on 2026-05-22 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=300)),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.userprofile')),
            ],
        ),
    ]
